package Practica3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import javax.swing.JOptionPane;

/**
 *
 * @author invitado
 */
public class Frases extends javax.swing.JFrame {

    /**
     * Creates new form Frases
     */
    public Frases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btEn = new javax.swing.JButton();
        btnAb = new javax.swing.JButton();
        btnJul = new javax.swing.JButton();
        btnOc = new javax.swing.JButton();
        btnFeb = new javax.swing.JButton();
        btnMa = new javax.swing.JButton();
        btnAgo = new javax.swing.JButton();
        btnNov = new javax.swing.JButton();
        btnMar = new javax.swing.JButton();
        btnJun = new javax.swing.JButton();
        btnSep = new javax.swing.JButton();
        btnDic = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 204));
        jLabel1.setText("Música");

        btEn.setForeground(new java.awt.Color(255, 153, 51));
        btEn.setText("Enero");
        btEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnActionPerformed(evt);
            }
        });

        btnAb.setForeground(new java.awt.Color(255, 0, 153));
        btnAb.setText("Abril");
        btnAb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbActionPerformed(evt);
            }
        });

        btnJul.setForeground(new java.awt.Color(0, 153, 153));
        btnJul.setText("Julio");
        btnJul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJulActionPerformed(evt);
            }
        });

        btnOc.setForeground(new java.awt.Color(51, 255, 51));
        btnOc.setText("Octubre");
        btnOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcActionPerformed(evt);
            }
        });

        btnFeb.setForeground(new java.awt.Color(255, 153, 0));
        btnFeb.setText("Febrero");
        btnFeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFebActionPerformed(evt);
            }
        });

        btnMa.setForeground(new java.awt.Color(255, 0, 102));
        btnMa.setText("Mayo");
        btnMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaActionPerformed(evt);
            }
        });

        btnAgo.setForeground(new java.awt.Color(0, 153, 153));
        btnAgo.setText("Agosto");
        btnAgo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgoActionPerformed(evt);
            }
        });

        btnNov.setForeground(new java.awt.Color(51, 255, 0));
        btnNov.setText("Noviembre");
        btnNov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovActionPerformed(evt);
            }
        });

        btnMar.setForeground(new java.awt.Color(255, 153, 51));
        btnMar.setText("Marzo");
        btnMar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarActionPerformed(evt);
            }
        });

        btnJun.setForeground(new java.awt.Color(255, 0, 51));
        btnJun.setText("Junio");
        btnJun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJunActionPerformed(evt);
            }
        });

        btnSep.setForeground(new java.awt.Color(0, 153, 153));
        btnSep.setText("Septiembre");
        btnSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSepActionPerformed(evt);
            }
        });

        btnDic.setForeground(new java.awt.Color(51, 255, 0));
        btnDic.setText("Diciembre");
        btnDic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicActionPerformed(evt);
            }
        });

        jButton13.setText("NO PULSAR");

        btnSig.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        btnSig.setText("Siguiente");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSig))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnAb)
                            .addComponent(btEn)
                            .addComponent(btnJul)
                            .addComponent(btnOc))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFeb)
                            .addComponent(btnMa)
                            .addComponent(btnAgo)
                            .addComponent(btnNov))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDic)
                            .addComponent(btnSep)
                            .addComponent(btnMar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnJun)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(jButton13)))))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEn)
                    .addComponent(btnFeb)
                    .addComponent(btnMar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAb)
                            .addComponent(btnMa)
                            .addComponent(btnJun)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton13)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnJul)
                    .addComponent(btnAgo)
                    .addComponent(btnSep))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOc)
                    .addComponent(btnNov)
                    .addComponent(btnDic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnSig)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnActionPerformed
        JOptionPane.showMessageDialog(null, "Te darás cuenta que lo que hoy parece un sacrificio, va a terminar siendo el mayor logro de tu vida");
    }//GEN-LAST:event_btEnActionPerformed

    private void btnAbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbActionPerformed
        JOptionPane.showMessageDialog(null, "Sing me a symphony, one for the lost and between, city of fallen dreams, city of angels");
    }//GEN-LAST:event_btnAbActionPerformed

    private void btnJulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJulActionPerformed
        JOptionPane.showMessageDialog(null, "May I hold you, as you fall asleep, when the world is closing in, and you can't breathe");
    }//GEN-LAST:event_btnJulActionPerformed

    private void btnOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcActionPerformed
        JOptionPane.showMessageDialog(null, "Lonely, finds me, one day, you will come, but I'll wait, for love sake, one day to me");
    }//GEN-LAST:event_btnOcActionPerformed

    private void btnFebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFebActionPerformed
        JOptionPane.showMessageDialog(null, "I will be a revolution, be a voice beyond this lies, I will not be lost in silence, I will not let darkness hides, there's hope beyond my sight");
    }//GEN-LAST:event_btnFebActionPerformed

    private void btnMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaActionPerformed
        JOptionPane.showMessageDialog(null, "My heart's crippled by the vain that I keep on closing, you cut me opne and I, keep bleeding love ");
    }//GEN-LAST:event_btnMaActionPerformed

    private void btnAgoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgoActionPerformed
        JOptionPane.showMessageDialog(null, "So why did I wish for a better a life, after everything that I couldn´t see it");
    }//GEN-LAST:event_btnAgoActionPerformed

    private void btnNovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovActionPerformed
        JOptionPane.showMessageDialog(null, "Some love lines I can't erease, some hearts strings I can't "
                + "replace, some bells, ring forever, but some day, could come");
    }//GEN-LAST:event_btnNovActionPerformed

    private void btnMarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarActionPerformed
        JOptionPane.showMessageDialog(null, "When stars fall, and ground breaks, you're sinking, 'cause it's too late, don't tell me, that is over, even though you're fighting hard to belive");
    }//GEN-LAST:event_btnMarActionPerformed

    private void btnJunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJunActionPerformed
        JOptionPane.showMessageDialog(null, "Smile, when you're not supposed to laugh, and cry when you're supposed to hold it back, and live like the sun is burning out of the sky");
    }//GEN-LAST:event_btnJunActionPerformed

    private void btnSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSepActionPerformed
        JOptionPane.showMessageDialog(null, "Tear me way from everything we've done, i guess that my wings has taken me close to your sun, twist every word to make them what you need, if you must walk alone, don't come running back to me");
    }//GEN-LAST:event_btnSepActionPerformed

    private void btnDicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicActionPerformed
        JOptionPane.showMessageDialog(null, "I can hear you say, it's a brand new day, the pain goes away, and I'm headed for the door");
    }//GEN-LAST:event_btnDicActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        Verdad_o_falso v = new Verdad_o_falso();
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEn;
    private javax.swing.JButton btnAb;
    private javax.swing.JButton btnAgo;
    private javax.swing.JButton btnDic;
    private javax.swing.JButton btnFeb;
    private javax.swing.JButton btnJul;
    private javax.swing.JButton btnJun;
    private javax.swing.JButton btnMa;
    private javax.swing.JButton btnMar;
    private javax.swing.JButton btnNov;
    private javax.swing.JButton btnOc;
    private javax.swing.JButton btnSep;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton jButton13;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
