/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Polimorfismo;
import Menu.Menu;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Ventana2 extends javax.swing.JFrame {
    /*Declararemos las variables para almacenar
    los datos que recibiremos de la Ventana1 para
    utilizarlos en nuestra ventana*/
    String nombre, apellido, adicional;
    int edad;
    boolean esAlumno;
    
    /**
     * Creates new form Ventana2
     */
    public Ventana2(String nombre, String apellido, int edad, String adicional, boolean esAlumno) {
        initComponents();
        /*Recibimos los atributos de la ventana 1 y lo almacenamos en las variables
        globales de arriba*/
        this.esAlumno = esAlumno;
        this.nombre = nombre;
        this.apellido = apellido;
        this.edad = edad;
        this.adicional = adicional;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMost = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMost.setText("Mostrar información");
        btnMost.setBorder(new javax.swing.border.MatteBorder(null));
        btnMost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 0, 24)); // NOI18N
        jLabel1.setText("¡PERSONA REGISTRADA CON EXITO!");

        jButton2.setText("Regresar al registro");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(btnMost, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(btnMost, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostActionPerformed
        if(esAlumno){
            Alumno persona = new Alumno(nombre, apellido, edad, adicional);
            JOptionPane.showMessageDialog(null, "Hola, ni nombre es "+persona.nombre+" "+persona.apellido+
                ", actualmente tengo "+persona.edad+" años y estudio en el TEC II con número de control "+persona.no_control+"\n"+
                "Método especifico de la subclase: "+persona.entregarTarea()+"\n"+
                "Método sobreescrito de la clase principal: "+persona.Ir_al_aula());
        }else{
            Profesor persona = new Profesor(nombre, apellido, edad, adicional);
            JOptionPane.showMessageDialog(null, "Hola, ni nombre es "+persona.nombre+" "+persona.apellido+
                ", actualmente tengo "+persona.edad+" años y doy clases en el TEC II en la materia de "+persona.materia+"\n"+
                "Método especifico de la subclase: "+persona.Calificar(8,5,8)+"\n"+
                "Método sobreescrito de la clase principal: "+persona.Ir_al_aula());
        }
        
    }//GEN-LAST:event_btnMostActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Ventana1 v1 = new Ventana1();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMost;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
